name: Actions (Build Kernel)

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  push:
  workflow_dispatch:

jobs:
  
  sm8150-lineage-22.1:
    uses: ./.github/workflows/sm8150-lineage-22-1-actions.yml

  noname-lineage-22.1:
    uses: ./.github/workflows/noname-lineage-22-1-actions.yml

  noname-lineage-18.1:
    uses: ./.github/workflows/noname-lineage-18-1-actions.yml

  noname-vic:
    uses: ./.github/workflows/noname-vic-actions.yml
  
