name: Actions (Build Kernel)

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_call:
   inputs:
     kernel_url:
      type: string
      required: true
     kernel_branch:
      type: string
      required: true
     patches_url:
      type: string
      required: true
     patches_branch:
      type: string
      required: true
     anykernel_url:
      type: string
      required: true
     anykernel_branch:
      type: string
      required: true
     tag:
      type: string
      required: true
     ksu_url:
      type: string
      required: true
     ksu_branch:
      type: string
      required: true
     ksu_sus_b:
      type: string
      required: true
     defconfig:
      type: string
      required: true
     config:
      type: string
      required: false
jobs:

  kernel-separator:
   runs-on: ubuntu-latest
   steps:
     - name: Hello world
       run: |
         echo "Hello world"

  main:
    uses: ./.github/workflows/build.yml
    needs: kernel-separator
    secrets: inherit
    with:
      kernel_url: ${{ inputs.kernel_url }}
      kernel_branch: ${{ inputs.kernel_branch }}
      patches_url: ${{ inputs.patches_url }}
      patches_branch: ${{ inputs.patches_branch }}
      anykernel_url: ${{ inputs.anykernel_url }}
      anykernel_branch: ${{ inputs.anykernel_branch }}
      tag: ${{ inputs.tag }}
      defconfig: ${{ inputs.defconfig }}
      config: ${{ inputs.config }}
      ksu_url: "false"
      susfs: "false"
      build_type: ""

  ksunextsusfs:
    uses: ./.github/workflows/build.yml
    needs: kernel-separator
    secrets: inherit
    with:
      kernel_url: ${{ inputs.kernel_url }}
      kernel_branch: ${{ inputs.kernel_branch }}
      patches_url: ${{ inputs.patches_url }}
      patches_branch: ${{ inputs.patches_branch }}
      anykernel_url: ${{ inputs.anykernel_url }}
      anykernel_branch: ${{ inputs.anykernel_branch }}
      tag: ${{ inputs.tag }}
      defconfig: ${{ inputs.defconfig }}
      config: ${{ inputs.config }}
      ksu_url: ${{ inputs.ksu_url }}
      ksu_branch: ${{ inputs.ksu_sus_b }}
      susfs: "true"
      build_type: "-[KSUNext-SUSFS]"

  ksunext:
    uses: ./.github/workflows/build.yml
    needs: kernel-separator
    secrets: inherit
    with:
      kernel_url: ${{ inputs.kernel_url }}
      kernel_branch: ${{ inputs.kernel_branch }}
      patches_url: ${{ inputs.patches_url }}
      patches_branch: ${{ inputs.patches_branch }}
      anykernel_url: ${{ inputs.anykernel_url }}
      anykernel_branch: ${{ inputs.anykernel_branch }}
      tag: ${{ inputs.tag }}
      defconfig: ${{ inputs.defconfig }}
      config: ${{ inputs.config }}
      ksu_url: ${{ inputs.ksu_url }}
      ksu_branch: ${{ inputs.ksu_branch }}
      susfs: "false"
      build_type: "-[KSUNext]"

