 name: Kernel Build
 on:
  workflow_dispatch:
  pull_request:
  push:
 jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
     matrix:
      kernel_config:
       - kernel_name: "SM6125"
         kernel_url: "https://github.com/Skyblueborb/android_kernel_xiaomi_sm6125"
         kernel_branch: "lineage-22.2-common"
         anykernel_branch: "sm6125"
         tag: "[SM6125-LOS-22.2]"
         defconfig: "vendor/trinket-perf_defconfig"
         config: "vendor/laurel_sprout.config"
         patches_folder: "sm6125"

       - kernel_name: "Snowflake"
         kernel_url: "https://github.com/liquidprjkt/snowflake_laurel_sprout"
         kernel_branch: "snowflake_noname"
         tag: "[Snowflake]"
         defconfig: "vendor/laurel_sprout-perf_defconfig"

       - kernel_name: "NoName-LOS-22.1"
         kernel_url: "https://github.com/TheSillyOk/kernel_xiaomi_laurel_sprout-noname"
         kernel_branch: "heresy"
         tag: "[NoName-LOS-22.1]"

       - kernel_name: "NoName-LOS-18.1"
         kernel_url: "https://github.com/TheSillyOk/kernel_laurel_sprout" 
         kernel_branch: "lineage-18.1"
         tag: "[NoName-LOS-18.1]"

       - kernel_name: "NoName-VIC"
         kernel_url: "https://github.com/TheSillyOk/kernel_laurel_sprout" 
         kernel_branch: "vic"
         tag: "[NoName-VIC]"

      build_type: ["Normal", "KSU", "KSUN", "RKSU"]
      susfs: [false, true]
      exclude:
           - build_type: "Normal"
             susfs: true
    permissions:
      contents: write
    steps:
      - name: Output configs
        id: variable
        run: |

          set_config() {
            local name="$1"
            local default_value="$2"
            local value="$3"
            
            ENV_NAME=$name

            if [[ "$name" == *"branch"* && "$value" == *"-b " ]]; then
              echo "$ENV_NAME=$default_value" >> $GITHUB_ENV
              echo "-> Set $name value to \"$default_value\""
            else
             if [ -z "$value" ]; then
              echo "$ENV_NAME=$default_value" >> $GITHUB_ENV
              echo "-> Set $name value to \"$default_value\""
             else
               echo "$ENV_NAME=$value" >> $GITHUB_ENV
               echo "-> Set $name value to \"$value\""
             fi
            fi
          }

          set_config "defconfig" "vendor/laurel_sprout-perf_defconfig" "${{ matrix.kernel_config.defconfig }}"
          set_config "config" "${{ matrix.kernel_config.config }}"

          set_config "patches_url" "https://github.com/TheSillyOk/kernel_ls_patches" "${{ matrix.kernel_config.patches_url }}"
          set_config "patches_branch" "" " -b ${{ matrix.kernel_config.patches_branch }}"
          set_config "patches_folder" "noname" "${{ matrix.kernel_config.patches_folder }}"

          set_config "anykernel_url" "https://github.com/TheSillyOk/anykernel" "${{ matrix.kernel_config.anykernel_url }}"
          set_config "anykernel_branch" "" " -b ${{ matrix.kernel_config.anykernel_branch }}"

          set_config "kernel_branch" "" " -b ${{ matrix.kernel_config.kernel_branch }}"


      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: Initialize workspace and tools
        id: workspace
        run: |
          set -e
          # Define an absolute workspace folder inside the GitHub workspace
          WORKSPACE_FOLDER="${GITHUB_WORKSPACE}/workspace"
          mkdir -p "$WORKSPACE_FOLDER"
          echo "workspace-folder=$WORKSPACE_FOLDER" >> $GITHUB_OUTPUT
          echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

          sudo apt-get update -y -qq
          sudo apt-get install -y --no-install-recommends \
            python3-pip \
            git \
            zip \
            unzip \
            gcc \
            g++ \
            make \
            ninja-build \
            file \
            bc \
            bison \
            flex \
            libfl-dev \
            libssl-dev \
            libelf-dev \
            wget \
            build-essential \
            python3-dev \
            python3-setuptools \
            rsync \
            ccache \
            llvm-dev

          sudo apt install libncurses6 libfdt-dev
          # Also output a tools folder variable (same as workspace here)
          echo "tools-folder=$WORKSPACE_FOLDER" >> $GITHUB_OUTPUT

      - name: Cache Clang
        uses: actions/cache@v4
        id: cache-clang
        with:
          path: ${{ steps.workspace.outputs.workspace-folder }}/clang
          key: clang-r547379-ubuntu-latest
          restore-keys: |
            clang-r547379-ubuntu-latest
            clang-r547379-

      - name: Download and Extract Clang
        if: steps.cache-clang.outputs.cache-hit != 'true'
        working-directory: ${{ steps.workspace.outputs.workspace-folder }}
        run: |
          set -e
          echo "Downloading and extracting clang..."
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
          mkdir -p clang
          tar -xf clang.tar.gz -C clang
          echo "Clang downloaded and extracted."

      - name: Set up ccache
        run: |
         ccache --version
         ccache --max-size=2G
         ccache --set-config=compression=true
         echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

      - name: Restore ccache from cache
        uses: actions/cache/restore@v4
        with:
         path: ~/.ccache
         key: ${{ matrix.build_type }}-${{ matrix.kernel_config.tag }}-SUSFS_${{ matrix.susfs }}-ccache-

      - name: Preparing kernel
        id: kernel
        run: |
          set -e
 
          WORKSPACE_FOLDER="${{ steps.workspace.outputs.workspace-folder }}"

          git clone --depth=1 "${{ matrix.kernel_config.kernel_url }}"${{ env.kernel_branch }} "$WORKSPACE_FOLDER/kernel_tree"
          echo "kernel-folder=$WORKSPACE_FOLDER/kernel_tree" >> $GITHUB_OUTPUT
          KERNEL_FOLDER="$WORKSPACE_FOLDER/kernel_tree"
          cd "$KERNEL_FOLDER"

          git clone "${{ env.patches_url }}"${{ env.patches_branch }} "$WORKSPACE_FOLDER/kernel_patches"
          KERNEL_PATCHES_FOLDER="$WORKSPACE_FOLDER/kernel_patches"
          mkdir -p "$WORKSPACE_FOLDER/kernel_tree/common/fs" "$WORKSPACE_FOLDER/kernel_tree/common/include/linux"

           echo "--- Applying python3.patch... ---"
           patch -p1 -F 3 -N < "$WORKSPACE_FOLDER/kernel_patches/python3.patch" || true

           echo "--- Applying fix_lto.patch... ---"
           patch -p1 < "$WORKSPACE_FOLDER/kernel_patches/fix_lto.patch" || true

           sed -i 's/-dirty//' ./scripts/setlocalversion

           sed -i -E 's/^CONFIG_(LTO[^=]*|HAVE_LTO[^=]*|CC_OPTIMIZE_FOR[^=]*|MODVERSIONS)=(y|n)/# CONFIG_\1=\2/g' "arch/arm64/configs/${{ env.defconfig }}" && echo -e "\n\n# Workflow added configs #\nCONFIG_LTO_CLANG=y\nCONFIG_LTO_CLANG_THIN=y\nCONFIG_HAVE_LTO_CLANG=y\nCONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y\nCONFIG_MODVERSIONS=n" >> "arch/arm64/configs/${{ env.defconfig }}"

      - name: Apply KernelSU
        if: ${{ matrix.build_type != 'Normal' }}
        id: ksu
        run: |
          set -e

          WORKSPACE_FOLDER="${{ steps.workspace.outputs.workspace-folder }}"
          KERNEL_FOLDER="$WORKSPACE_FOLDER/kernel_tree"
          KERNEL_PATCHES_FOLDER="$WORKSPACE_FOLDER/kernel_patches"
          cd "$KERNEL_FOLDER"
          
          echo "Applying manual_hooks.patch..."
          patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/${{ env.patches_folder }}/manual_hooks.patch" || true

          echo "--- Setting up KernelSU: ${{ matrix.build_type }} ---"
          case "${{ matrix.build_type }}-${{ matrix.susfs }}" in
           KSU-*)
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/path_unmount.patch" || true
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/get_cred_rcu.patch"
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/strncpy_from_user_nofault.patch"
            cd KernelSU
           ;;
           KSUN-false)
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
            cd KernelSU-Next
           ;;
           KSUN-true)
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev
            cd KernelSU-Next
           ;;
           RKSU-false)
            curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/path_unmount.patch" || true
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/get_cred_rcu.patch"
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/strncpy_from_user_nofault.patch"
            cd KernelSU
           ;;
           RKSU-true)
            curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s susfs-v1.5.7
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/path_unmount.patch" || true
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/get_cred_rcu.patch"
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/strncpy_from_user_nofault.patch"
            cd KernelSU
           ;;
           *)
            echo "Invalid selection for build_type and/or susfs: ${{ matrix.build_type }}-${{ matrix.susfs }}"
           ;;
          esac
          echo "--- ${{ matrix.build_type }} setup complete ---"
           cd $KERNEL_FOLDER

          # Append configuration settings to the defconfig file
           sed -i -E 's/^CONFIG_(KPROBES|TMPFS_XATTR|KSU[^=]*)=(y|n)/# CONFIG_\1=\2/g' "arch/arm64/configs/${{ env.defconfig }}" && echo -e "\n\n# Workflow added configs #\nCONFIG_KPROBES=n\nCONFIG_KSU=y\nCONFIG_TMPFS_XATTR=y" >> "arch/arm64/configs/${{ env.defconfig }}"

      - name: Apply SUSFS
        if: ${{ matrix.susfs }}
        id: susfs
        run: |
          set -e

          WORKSPACE_FOLDER="${{ steps.workspace.outputs.workspace-folder }}"
          KERNEL_FOLDER="$WORKSPACE_FOLDER/kernel_tree"
          KERNEL_PATCHES_FOLDER="$WORKSPACE_FOLDER/kernel_patches"

          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b kernel-4.14 "$WORKSPACE_FOLDER/susfs4ksu"

          SUSFS4KSU_PATCHES_FOLDER="$WORKSPACE_FOLDER/susfs4ksu/kernel_patches"

          cp -r $SUSFS4KSU_PATCHES_FOLDER/fs/* $KERNEL_FOLDER/fs/
          cp -r $SUSFS4KSU_PATCHES_FOLDER/include/linux/* $KERNEL_FOLDER/include/linux

          cd "$KERNEL_FOLDER"
          echo "--- Applying SUSFS and Hide Stuff Patches ---"

          echo "--- Applying 50_add_susfs.patch... ---"
          patch -p1 -F 3 -N < "$SUSFS4KSU_PATCHES_FOLDER/50_add_susfs_in_kernel-4.14.patch" || true

          echo "--- Applying fix_susfs_rejects.patch... ---"
          patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/${{ env.patches_folder }}/fix_susfs_rejects.patch" || true

          echo "Applying 69_hide_stuff.patch..."
          patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/69_hide_stuff.patch" || true

          echo "--- Applying additional ${{ matrix.build_type }} patches... ---"
          case "${{ matrix.build_type }}" in
            KSU)        
             cd KernelSU
             patch -p1 -F 3 -N < "$SUSFS4KSU_PATCHES_FOLDER/KernelSU/10_enable_susfs_for_ksu.patch"
            ;;
            RKSU)
             patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/BACKPORT-SUSFS-v1.5.7-NON-GKI-4.14.patch"
            ;;
            KSUN)
              echo "--- Applying BACKPORT-fs-upstream-susfs-v1.5.7-new-non-gki.patch... ---"
              patch -p1 -F 3 -N < "$KERNEL_PATCHES_FOLDER/BACKPORT-fs-upstream-susfs-v1.5.7-new-non-gki.patch" || true
          esac
          echo "--- Additional ${{ matrix.build_type }} patches applied ---"
          cd $KERNEL_FOLDER


          echo "--- SUSFS and Hide Stuff Patches applied ---"
          echo -e "\nCONFIG_KSU_SUSFS=y" >> "arch/arm64/configs/${{ env.defconfig }}"


      - name: Building kernel
        id: build
        run: |
          set -e
          # Use absolute paths for the kernel folder and tools folder
          KERNEL_FOLDER="${{ steps.kernel.outputs.kernel-folder }}"
          TOOLS_FOLDER="${{ steps.workspace.outputs.tools-folder }}"
          cd $KERNEL_FOLDER

          if [[ "${{ matrix.kernel_config.tag }}" == *"SM6125"* ]]; then
           EXTRA=" DTC_PREBUILT=true DTC=$KERNEL_FOLDER/dtc/dtc DTC_OVERLAY_TEST_EXT=$KERNEL_FOLDER/libufdt/ufdt_apply_overlay MKDTIMG=$KERNEL_FOLDER/libufdt/mkdtimg"
           wget https://android.googlesource.com/platform/prebuilts/misc/+archive/refs/tags/android-15.0.0_r26/linux-x86.tar.gz -O androd.tar.gz
           tar -xzf androd.tar.gz
           git clone https://github.com/TheSillyOk/kernel_extra -b main extra
           rm dtc/dtc && mv extra/dtc dtc/dtc
           chmod +x dtc/dtc
          else
           EXTRA=""
          fi

          echo "Building kernel using absolute paths..."
          export CCACHE_EXEC=$(which ccache)
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Ok"
          export KBUILD_BUILD_HOST="Github"
          export PATH="$TOOLS_FOLDER/clang/bin:$PATH"
          BUILD_START_TIME=$(date +%s)

          mkdir -p "$KERNEL_FOLDER/artifacts"

          make O="$KERNEL_FOLDER/out" ARCH=arm64 ${{ env.defconfig }} ${{ env.config }}
          make O="$KERNEL_FOLDER/out"$EXTRA CC="ccache clang" LD=ld.lld LLVM=1 LLVM_IAS=1 -j"$(nproc --all)" CROSS_COMPILE=aarch64-linux-gnu-

          BUILD_END_TIME=$(date +%s)
          DIFF=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "elapsed_time=$DIFF" >> $GITHUB_OUTPUT
          echo -e "Build completed in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds."

      - name: Save ccache to cache
        uses: actions/cache/save@v4
        with:
         path: ~/.ccache
         key: ${{ matrix.build_type }}-${{ matrix.kernel_config.tag }}-SUSFS_${{ matrix.susfs }}-ccache-${{ github.sha }}-${{ github.run_number }}

      - name: Handle AnyKernel3 zips
        id: anykernel
        run: |
          set -e
          KERNEL_FOLDER="${{ steps.kernel.outputs.kernel-folder }}"
          BOOT_FOLDER="$KERNEL_FOLDER/out/arch/arm64/boot"
          cd "$BOOT_FOLDER"

          git clone --recursive --depth=1 "${{ env.anykernel_url }}"${{ env.anykernel_branch }} "$BOOT_FOLDER/ak_folder"

          if [ -e "$BOOT_FOLDER/Image.gz-dtb" ]; then
            cp -f "$BOOT_FOLDER/Image.gz-dtb" "$BOOT_FOLDER/ak_folder"
          else

           if [ -e "$BOOT_FOLDER/Image.gz" ]; then
             cp -f "$BOOT_FOLDER/Image.gz" "$BOOT_FOLDER/ak_folder"
           fi

          fi

          if [ -e "$BOOT_FOLDER/dtbo.img" ]; then
            cp -f "$BOOT_FOLDER/dtbo.img" "$BOOT_FOLDER/ak_folder"
          fi

          case "${{ matrix.build_type }}-${{ matrix.susfs }}" in
           KSUN-false)
            BUILD="-[KSUNext]"
           ;;
           KSUN-true)
            BUILD="-[KSUNext-SUSFS]"
           ;;
           KSU-false)
            BUILD="-[KSU]"
           ;;
           KSU-true)
            BUILD="-[KSU-SUSFS]"
           ;;
           RKSU-false)
            BUILD="-[RKSU]"
           ;;
           RKSU-true)
            BUILD="-[RKSU-SUSFS]"
           ;;
           Normal*)
            BUILD=""
           ;;
           *)
            BUILD=""
            echo "Invalid selection for build_type and/or susfs: ${{ matrix.build_type }}-${{ matrix.susfs }}"
           ;;
          esac


          date="$(date +"%d%m%Y")"
          zip_name="$date-MiA3$BUILD-${{ matrix.kernel_config.tag }}-${{ github.run_number }}"
          mkdir release
          rm -rf ak_folder/*.git*
          cp -r ak_folder/* release
          echo "anykernel_zipname=$zip_name" >> $GITHUB_OUTPUT

      - name: Upload AnyKernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.anykernel.outputs.anykernel_zipname }}
          path: |
            ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/release/


#      - name: Upload to Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/${{ steps.anykernel.outputs.anykernel_zipname }}
#            ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/${{ steps.second_anykernel.outputs.second_anykernel_zipname }}
#          name: laurel_sprout-${{ github.run_id }}
#          tag_name: ${{ github.run_id }}
#          body: |
#            <b>${{ steps.workspace.outputs.build_title }}</b>
#            <b>Kernel successfully built!</b>, took ${{ steps.build.outputs.elapsed_time }} seconds.
#
#            <b>Kernel tree</b>: https://github.com/TheSillyOk/kernel_laurel_sprout/tree/lineage-22.1
#            <b>Action</b>: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
