name: Scheduled Build

permissions:
  contents: write
  actions: write
on:
  workflow_dispatch:
  schedule:
   - cron: "0 12 * * *"
jobs:
     build:
      uses: ./.github/workflows/build_kernels.yml
      secrets: inherit
      with:
       scheduled: true
